{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "koobeye-kubernetes-agent-helm-chart.serviceAccountName" . }}-crb
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "koobeye-kubernetes-agent-helm-chart.serviceAccountName" . }}-cr
subjects:
  - kind: ServiceAccount
    name: {{ include "koobeye-kubernetes-agent-helm-chart.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
